version: '3.8'
services:
  php:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: php-backend
    volumes:
      - .:/var/www/html
    ports:
      - "8080:80" # Maps localhost:8080 to the container's port 80
    depends_on:
      - db
    networks:
      - backend

  db:
    image: mysql:8.0
    container_name: mysql-db
    environment:
      MYSQL_ROOT_PASSWORD: root_password
      MYSQL_DATABASE: scandiweb
      MYSQL_USER: user
      MYSQL_PASSWORD: user_password
    ports:
      - "3306:3306"
    volumes:
      - ./db/scripts:/docker-entrypoint-initdb.d 
    networks:
      - backend
      
networks:
  backend:
    driver: bridge

volumes:
  mysql_data: